### ISSUE TITLE
404 accessing tutorial VM

### ISSUE THREAD

**Issue by olorin** [frenetic-lang/tutorials#7]
https://github.com/frenetic-lang/tutorials/commit/af25762bc82cc95a62778e794fdb3a5c5cebc335#diff-9f2b8f4279fc829a614a6b36a2594551R49 links to http://storage.googleapis.com/arjun-umass-disks/Frenetic-Tutorial.ova, which does not exist.

**Comment by jnfoster** [comment]
Thanks. We'll fix this. In the meantime, I suggest using the frenetic-lang/frenetic-vm Vagrant script to build a VM.

-N

**Comment by arjunguha** [comment]
sorry, this is my fault. i'll fix it.

**Comment by J2501** [comment]
My Vagrant install is broken, I would appreciate if you can fix this

**Comment by arjunguha** [comment]
Fixed! The linked OVA is basically Lubuntu 14.04 initialized with the scripts from the frenetic-vm repository.
